### PR TITLE
Library structure

### PR DESCRIPTION
**Pull request by kravets-levko**
Improvements to the library's structure:

1. Styles: extracted inline styles to files (and converted to Less), used `bootstrap` and `bootstrap-rtl` as dependencies. Put compiled styles into `lib/styles`.
2. Used `webpack-dev-server` for development - `npm start` will compile files in-memory and serve them. Also it will watch for changes and automatically refresh browser.
3. Removed unnecessary files, update `.*ignore` files and README.
4. Added instructions for using the library, development, etc.
5. Library version updated.

Also, affects OpenBudget/budgetkey-ng2-components/issues/1

### CODE REVIEW

**Comment by akariv** [comment]
@kravets-levko can we add a simple .travis.yml file as well?

**Review by akariv — APPROVED** [review]
LGTM!

**Comment by kravets-levko** [comment]
@akariv Okay, will add and then ping you. Is the README good enough?

**Comment by kravets-levko** [comment]
@akariv I added simple `.travis.yml`, so now build is successful. Probably it will be a good point to add some tests in future, but it's not a subject of this PR.

**Comment by OriHoch** [comment]
@akariv @kravets-levko have you tested this with the apps? I think currently it's not possible to integrate version after this changes with the apps..
the documentation in the README didn't work - it seems the changed structure requires changes in the apps as well..

**Pull request merged**
