### PR TITLE
[Preview] [Work In Progress] Open procurement fork

### PR DESCRIPTION
**Pull request by OriHoch**
**Do Not Merge**

This is a work in progess to allow customizing header / footer for another site which will use the same budgetkey apps and components

Because there is not much code in the ng2-components I think it would be best to fork this repo into `openprocurement-ng2-components` and corresponding [npm package](https://www.npmjs.com/package/openprocurement-ng2-components)

### CODE REVIEW

**Comment by OriHoch** [comment]
@akariv @kravets-levko let me know what you think..

**Comment by kravets-levko** [comment]
I think, it depends on two things:

- how much mentioned components will be customized (amount of changes), and
- in which way they will be customized (a kind of config file, editing code, etc. - depends on item 1).

If the idea is to slightly modify the components - it definitely should be a fork. On small modifications (i.e. custom color schema) - I think it would be better to keep it all in the single repo.

**Comment by akariv** [comment]
I think that if we're talking about modifying the title, logo and color-scheme, we shouldn't fork this repo at all - but pass them as parameters to the component.

This will also ensure that the two themes never drift too much apart from one another.

**Review by akariv — CHANGES_REQUESTED** [review]
See my comment in the conversation tab

**Comment by OriHoch** [comment]
replacement PR: #4

**Pull request closed without merging**
